markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 12
paginate_path: page/:num

blog:
    name: chrispher guan
    description: Data Science
    title: Data Science
    url: http://chrispher.github.com 
    duoshuo: chrispher2012
    tongji: 3Fca70591450b95f8b7d7de185c49db345
author:
    # Profile links on the left sidebar, leave blank to ignore
    name: chrispher guan 
    email: chrispher2012@gmail.com 
    weibo: 2917650677  # weibo ID
    github: chrispher  # github ID
    linkedin: chrispher-guan/5a/a68/6b8
    gplus: 110552447039675960964
    logo: http://chrispher.github.com/res/img/logo.png
    ads: http://chrispher.github.com/res/img/ads.jpg
    ads_text: 永远相信美好的事物即将发生！
