markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 15
paginate_path: page/:num

blog:
    name: Data Science
    description: chrispher2012
    title: Data Science
    url: http://chrispher.github.io 
    duoshuo: chrispher2012
    tongji: 5565556 
author:
    name: chrispher guan 
    email: chrispher2012@gmail.com 
    weibo: http://weibo.com/u/2917650677
    github: https://github.com/chrispher
    logo: http://chrispher.github.com/images/op_we_are_brothers.png
