markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name: chrispher
    description: Data Science
    title: Data Science
    keywords: Data Science
    url: http://localhost:4000
    # http://chrispher.github.com 
author:
    duoshuo: chrispher2012
    name: chrispher guan 
    email: chrispher2012@gmail.com 
    weibo: 2917650677
    github: chrispher
    linkedin: chrispher-guan/5a/a68/6b8
