markdown: kramdown
highlighter: pygments

# 分页设置
permalink: blog/:year/:month/:day/:title.html
paginate: 12
paginate_path: page/:num

blog:
    name: chrispher
    description: Data Science
    title: Data Science
    keywords: Data Science
    url: http://chrispher.github.com 

author:
    duoshuo: chrispher2012
    name: chrispher guan 
    email: chrispher2012@gmail.com 
    weibo: 2917650677
    github: chrispher
    linkedin: chrispher-guan/5a/a68/6b8

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed
