markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 15
paginate_path: page/:num

blog:
    name: chrispher2012
    description: Data Science
    title: Walking on my way 
    url: http://chrispher.github.io 
    duoshuo: chrispher2012
    tongji: chrispher2012 
author:
    name: chrispher guan 
    email: chrispher2012@gmail.com 
    weibo: http://weibo.com/u/2917650677
    github: https://github.com/chrispher
    logo: http://chrispher.github.com/images/op_we_are_brothers.png
