markdown: rdiscount
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 10
paginate_path: "page:num"

# presonal config
title: Steven Pan's Blog
description: Chrispher Guan's Blog, powered by Jekyll...
feed: http://chrispher.github.io//atom.xml

author: Chrispher Guan

seo: 
  keyword: blog
  description: Chrispher Guan's Blog, powered by Jekyll...